/**
 * DISPLAY_BLOCK content rendering (Phase 2 §6.9): a limited Markdown subset —
 * bold, italic, links, unordered/ordered lists, line breaks. No raw HTML
 * pass-through, no images, no headings. Author content is untrusted: the
 * source is entity-escaped FIRST, and every tag in the output is generated by
 * this module, so no author-controlled markup can survive. Links only allow
 * http/https/mailto and render with rel="noopener noreferrer" target="_blank".
 *
 * Shared by the live renderer and the editor preview so both sanitize
 * identically.
 */

function escapeHtml(text: string): string {
  return text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

const SAFE_URL = /^(https?:\/\/|mailto:)/i;

/** Inline markup on already-escaped text: links, bold, italic. */
function renderInline(escaped: string): string {
  let out = '';
  let rest = escaped;
  // Links first so bold/italic can nest inside the link text.
  const linkPattern = /\[([^\]]+)\]\(([^()\s]+)\)/;
  while (rest.length > 0) {
    const match = linkPattern.exec(rest);
    if (!match) {
      out += renderEmphasis(rest);
      break;
    }
    out += renderEmphasis(rest.slice(0, match.index));
    // The URL was escaped with the rest of the source; undo &amp; for the
    // scheme check, keep the escaped form in the attribute.
    const url = match[2];
    if (SAFE_URL.test(url.replaceAll('&amp;', '&'))) {
      out += `<a href="${url}" rel="noopener noreferrer" target="_blank">${renderEmphasis(match[1])}</a>`;
    } else {
      out += renderEmphasis(match[0]);
    }
    rest = rest.slice(match.index + match[0].length);
  }
  return out;
}

function renderEmphasis(escaped: string): string {
  return escaped
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    .replace(/_([^_]+)_/g, '<em>$1</em>');
}

const UL_ITEM = /^\s*[-*]\s+(.*)$/;
const OL_ITEM = /^\s*\d+[.)]\s+(.*)$/;

/**
 * Renders the markdown subset to a sanitized HTML string. The output contains
 * only <p> <br> <strong> <em> <a> <ul> <ol> <li> with fixed attributes.
 */
export function renderMarkdown(source: string): string {
  const lines = (source ?? '').replaceAll('\r\n', '\n').split('\n');
  const blocks: string[] = [];
  let paragraph: string[] = [];
  let list: { ordered: boolean; items: string[] } | null = null;

  const flushParagraph = () => {
    if (paragraph.length > 0) {
      blocks.push(`<p>${paragraph.map((l) => renderInline(escapeHtml(l))).join('<br>')}</p>`);
      paragraph = [];
    }
  };
  const flushList = () => {
    if (list) {
      const tag = list.ordered ? 'ol' : 'ul';
      blocks.push(`<${tag}>${list.items.map((i) => `<li>${i}</li>`).join('')}</${tag}>`);
      list = null;
    }
  };

  for (const line of lines) {
    const ul = UL_ITEM.exec(line);
    const ol = ul ? null : OL_ITEM.exec(line);
    if (ul || ol) {
      flushParagraph();
      const ordered = ol !== null;
      if (!list || list.ordered !== ordered) {
        flushList();
        list = { ordered, items: [] };
      }
      list.items.push(renderInline(escapeHtml((ul ?? ol)![1])));
    } else if (line.trim().length === 0) {
      flushParagraph();
      flushList();
    } else {
      flushList();
      paragraph.push(line);
    }
  }
  flushParagraph();
  flushList();
  return blocks.join('');
}
